schema: https://wpdlf.tkvw.nl/graphql
documents: src/queries.graphql
extensions:
  codegen:
    generates:
      ./src/schema.graphql:
        plugins:
          - schema-ast
      ./src/lib/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - "@tkvw/rxjs-apollo-codegen"
        config:
          clientPath: './client'
          queryOperationPrefix: 'use'
          queryOperationSuffix: 'Query'
          mutationOperationPrefix: 'use'
          mutationOperationSuffix: 'Mutation'
          fragmentVariableSuffix: 'Fragment'
          documentVariableSuffix: 'Document'